"""Exact finite checks supporting UNIFORM_ENERGY_COUNTEREXAMPLE.md.

The huge asymptotic A_d are defined deterministically in the proof, not
generated by this script. No finite output is an asymptotic proof.
"""
from fractions import Fraction as F
from itertools import combinations, product
from math import comb, isqrt
import json


def prime(n):
    if n<2:return False
    if n%2==0:return n==2
    return all(n%k for k in range(3,isqrt(n)+1,2))


def next_prime(n):
    q=n+1
    if q%2==0:q+=1
    while not prime(q):q+=2
    return q


def digit_windows():
    records=[]
    for d in range(2,6):
        D=8**d;p=next_prime(100*D*D)
        assert 100*D*D<p<200*D*D
        freqs=[(p+8**j-1)//8**j for j in range(1,d+1)]
        assert D-1<F(p,3) and p*3//16<F(p,3)
        observed={x for x in range(D) if all(xi*x%p<=3*p//16 for xi in freqs)}
        expected={sum(bit*8**i for i,bit in enumerate(bits))
                  for bits in product((0,1),repeat=d)}
        assert observed==expected and len(observed)==2**d
        assert not any(x!=y and (2*y-x)%p in observed for x in observed for y in observed)
        n=len(observed);k=n//d;a=F(k,n)
        assert F(1,2*d)<=a<=F(1,d) and 0<a<=F(4,5)
        # All APs in Omega are diagonal; exact old-cutoff obstruction.
        C=F(n,p*p);w=F(n,p);beta=C/(w*w)
        assert beta==F(1,n) and a**3*n*beta==a**3<8
        assert n<8*3**(d+1)/a**3
        records.append({'d':d,'p':p,'window_size':n,'window_rank_at_most':d+1,
                        'target_subset_size':k,'relative_density':str(a),
                        'window_3AP_free':True,'old_size_cutoff_satisfied':False,
                        'asymptotic_A_d_generated':False})
    return records


def canonical(labels):
    cells={}
    for i,label in enumerate(labels):cells.setdefault(label,[]).append(i)
    return tuple(sorted(tuple(cell) for cell in cells.values()))


def arc_state_enumeration():
    cases=0
    for p in (5,7,11):
        for b in (2,3,4):
            for gamma in range(p):
                coarse={canonical([((2*b*gamma*x-t)%(2*b*p))//(2*p) for x in range(p)])
                        for t in range(2*b*p)}
                finer={canonical([((6*b*gamma*x-t)%(6*b*p))//(6*p) for x in range(p)])
                       for t in range(6*b*p)}
                assert finer==coarse
                assert len(coarse)<=2*b*p
                cases+=1
    return cases


def fixed_size_partition_energy():
    cases=0
    for p,points in ((13,[0,1,3,9]),(31,[0,1,8,9])):
        n=len(points)
        partitions={canonical([((8*gamma*x-t)%(8*p))//(2*p) for x in points])
                    for gamma in range(p) for t in range(8*p)}
        for cells in partitions:
            M=len(cells)
            for k in range(1,n):
                a=F(k,n);total=F(0)
                for occupied in combinations(range(n),k):
                    A=set(occupied)
                    energy=sum(F(len(S),n)*(F(len(A.intersection(S)),len(S))-a)**2 for S in cells)
                    alternate=sum(F((n*len(A.intersection(S))-k*len(S))**2,
                                    n**3*len(S)) for S in cells)
                    assert alternate==energy
                    total+=energy
                assert total/comb(n,k)==a*(1-a)*F(M-1,n-1)
                cases+=1
    for n in range(2,25):
        for k in range(1,n):
            mode=F(comb(n,k)*k**k*(n-k)**(n-k),n**n)
            assert mode>=F(1,n+1)
    return cases


def asymptotic_bounds():
    rows=[]
    for d in (64,128,256,512,1024,4096):
        s=isqrt(d)
        ratio=F(64*d**4*d**s,2**d)
        n=d.bit_length()-1
        assert 2**n==d
        power=6+4*n+n*s-d
        assert ratio==(F(2**power) if power>=0 else F(1,2**(-power)))
        rows.append({'d':d,'characters_controlled':s,'arc_counts_controlled_up_to':d,
                     'variance_over_a_squared_upper_bound':'2^'+str(power),
                     'bound_only_not_generated_set':True})
    return rows


def main():
    print(json.dumps({'status':'finite construction checks passed; unrestricted energy lemma refuted by the written proof',
                      'digit_windows':digit_windows(),'arc_state_cases':arc_state_enumeration(),
                      'fixed_size_partition_cases':fixed_size_partition_energy(),
                      'asymptotic_bound_diagnostics':asymptotic_bounds(),
                      'arithmetic':'exact integers and rational numbers',
                      'target_r4_status':'OPEN','cutoff_qualified_energy_status':'OPEN',
                      'external_dependencies':[]},indent=2))


if __name__=='__main__':main()
